### PR TITLE
fix: exclude externalRef nodes from applySet to prevent empty CRs

### LINKED ISSUE #788: The externalRef attribute creates an empty resource.
### Description

externalRef creates an empty resource containing only meta tags from KRO. The original example https://kro.run/examples/basic/optionals/ first created the RGD resource without creating a ConfigMap.

After deploying, rgd created a ConfigMap even though it should only reference it.

Further development: I can't reference a previously created resource of another RGD using externalRef.

Kro v0.5.1-0.6.0 
EKS v1.34

deploymentservice-rg.yaml
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: deploymentservice
spec:
  schema:
    apiVersion: v1alpha1
    kind: DeploymentService
    spec:
      name: string
  resources:
    - id: input
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: demo
          namespace: kraken
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              containers:
                - name: ${schema.spec.name}-busybox
                  image: busybox
                  command: ["sh", "-c", "echo $MY_VALUE && sleep 3600"]
                  env:
                    - name: MY_VALUE
                      value: "Hello"
```

deployment.yaml
```
apiVersion: kro.run/v1alpha1
kind: DeploymentService
metadata:
  name: demo-kraken
spec:
 name: demo
```

k apply -f deploymentservice-rg.yaml
k apply -f deployment.yaml

k get cm
```
NAME                  DATA   AGE
demo                  0      11s
```

k get cm demo -o yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-10T15:16:01Z"
  labels:
    applyset.kubernetes.io/part-of: applyset-apGJ-ugQ359c8JITzcfDGct5Qf8askWpQGn0-pJ9AXo-v1
    kro.run/instance-id: 285c0ae9-7d53-48e1-93c6-8f4e9febdec2
    kro.run/instance-name: demo-kraken
    kro.run/instance-namespace: kraken
    kro.run/kro-version: v0.6.0-dirty
    kro.run/owned: "true"
    kro.run/resource-graph-definition-id: 5d1c9fa3-56ed-489e-b17d-a1f508e7acaa
    kro.run/resource-graph-definition-name: deploymentservice
  name: demo
  namespace: kraken
  resourceVersion: "1457192978"
  uid: 25f1bed3-4fd9-4ce2-8dc0-b721a648bc85
```

### PR DESCRIPTION
**Pull request by bschaatsbergen**
Closes #788
Relates to #780

External reference nodes (`externalRef`) were incorrectly included in the apply set after topological sorting, causing unwanted labels to be added and empty custom resources to be created during server-side apply. This change fixes the apply set construction by skipping external reference nodes entirely, ensuring only actual resources are applied while preserving the DAG processing order and labeling behavior.

### CODE REVIEW

File: pkg/controller/instance/controller_reconcile.go [hunk 1]
```diff
@@ -548,6 +566,35 @@ func (igr *instanceGraphReconciler) delayedRequeue(err error) error {
...
+	restMapping, err := igr.restMapper.RESTMapping(gvk.GroupKind(), gvk.Version)
+	if err != nil {
+		return nil, fmt.Errorf("failed to get REST mapping for %v: %w", gvk, err)
+	}
+
+	var dynResource dynamic.ResourceInterface
+	if restMapping.Scope.Name() == meta.RESTScopeNameNamespace {
+		namespace := resource.GetNamespace()
+		if namespace == "" {
+			namespace = metav1.NamespaceDefault
```
Comment (a-hilaly) [inline pkg/controller/instance/controller_reconcile.go]: I think we should default to the instance namespace.

File: pkg/controller/instance/controller_reconcile.go
Comment (a-hilaly) [inline pkg/controller/instance/controller_reconcile.go:1]: Can we get an integrations test for externalRefs?

Comment (a-hilaly) [reply pkg/controller/instance/controller_reconcile.go:1]: Maybe just update this one https://github.com/kubernetes-sigs/kro/blob/main/test/integration/suites/core/externalref_test.go - making sure that externalRefs do not get patched

**Comment by jakobmoellerdev** [comment]
e2e test added, just need an integration test now that fulfills the same purpose.

File: test/integration/suites/core/externalref_test.go [hunk 2]
```diff
@@ -128,6 +102,8 @@ var _ = Describe("ExternalRef", func() {
 			Expect(env.Client.Delete(ctx, rgd)).To(Succeed())
 		})
 
+		By("ensuring ResourceGraphDefinition is created and becomes active")
```
Comment (a-hilaly) [inline test/integration/suites/core/externalref_test.go:105]: TIL, `By` is a thing :)

File: pkg/controller/instance/controller_reconcile.go (hunk 1 above)
Comment (a-hilaly) [reply pkg/controller/instance/controller_reconcile.go]: can be addressed in a seperate PR.

File: pkg/controller/instance/controller_reconcile.go
Comment (a-hilaly) [reply pkg/controller/instance/controller_reconcile.go:1]: addressed in https://github.com/kubernetes-sigs/kro/pull/812/commits/80bcec10ab204c3dd98e64eab0f55e57eb2236c0

File: pkg/controller/instance/controller_reconcile.go [hunk 3]
```diff
@@ -570,7 +570,7 @@ func (igr *instanceGraphReconciler) delayedRequeue(err error) error {
 
 // readExternalRef fetches an external reference from the cluster.
 // External references are resources that exist outside of this instance's control.
-func (igr *instanceGraphReconciler) readExternalRef(ctx context.Context, resource *unstructured.Unstructured) (*unstructured.Unstructured, error) {
+func (igr *instanceGraphReconciler) readExternalRef(ctx context.Context, resourceID string, resource *unstructured.Unstructured) (*unstructured.Unstructured, error) {
```
Comment (a-hilaly) [inline pkg/controller/instance/controller_reconcile.go:573]: more reasons to rework the full reconciler/applyset :)
